### ISSUE TITLE
Liquid Syntax Error

### ISSUE THREAD

**Issue by Roprop** [kadaster/labs.kadaster.nl#4]
Collega's,

Als ik de docker file (lokaal) run krijg ik de volgende warning. Website lijkt er wel gewoon om te werken.

![image](https://user-images.githubusercontent.com/7302591/61949356-ee5ec480-afaa-11e9-8ea2-497c8ab4e3bc.png)

Fout is volgens mij ge-introduceerd in één van de laatste updates. Kan iemand er naar kijken?

**Comment by wouterbeek** [comment]
Dank voor het rapporteren.  Hier gaat Gerwin naar kijken.

**Comment by GerwinBosch** [comment]
@Roprop commit b8c3b67 zou het gefixt moeten hebben
